### ISSUE TITLE
No poseLib manager visible for me

### ISSUE THREAD

**Issue by energiesgraphiques** [jasperges/pose-thumbnails#15]
![presse-papiers-1](https://cloud.githubusercontent.com/assets/15011886/10334022/d12c33ca-6ce7-11e5-8f3b-ba61c5c0a3d5.jpg)
using Blender 2.76 RC1. I only get a grayed box

**Comment by jasperges** [comment]
At the moment you have to manually put images for your poses in the thumbnail folder. The automatic thumbnail generation is almost finished, but there are still some issues I have to fix before I merge the [auto create thumbnail branch](/jasperges/pose_lib_preview/tree/auto_create_thumbnail) in master. But if you want you can already try that branch.

**Comment by jasperges** [comment]
Closing this for now, because as far as I can tell, everything is working as expected.
