### ISSUE TITLE
poseLib table

### ISSUE THREAD

**Issue by energiesgraphiques** [jasperges/pose-thumbnails#16]
a thumnail table so we can directly clic on the one pose we want.
Exemple here : http://longwintermembers.com/wp-content/uploads/2014/08/2014-08-27_14h46_56.jpg

**Comment by jasperges** [comment]
When all the 'basics' are working correctly, I will have a look at this.

**Comment by sybrenstuvel** [comment]
Isn't this implemented already?

**Comment by jasperges** [comment]
What I think @energiesgraphiques would like, is to have the table expended the whole time. So you don't have to first click the thumbnail to see the table.
