### ISSUE TITLE
add a mix power slider

### ISSUE THREAD

**Issue by energiesgraphiques** [jasperges/pose-thumbnails#17]
add one "mix power" slider under the pose thumbnail list, so we can add 10% (or else) over the current pose.

**Comment by jasperges** [comment]
This means 'rewriting' the pose library functionality. At the moment I use Blender's own Pose Library functionality and this isn't supported. I think there are more enhancements that could be useful, which also require new Pose Library functionality. So I might end up making that someday… :)

**Comment by jasperges** [comment]
Closed by commit [73e9599](https://github.com/jasperges/pose_thumbnails/commit/73e9599958b3aa7c698fe7b959416aab4a1f9493) and improved by later commits.
