### ISSUE TITLE
Thumbnail shapekeys enhancement

### ISSUE THREAD

**Issue by belolo** [jasperges/pose-thumbnails#21]
HI!!! AWESOME ADDON, thank you so much for sharing it!, i have a request, can you please try to do the same for shapekeys?? thumbnails would be so awesome and would speed everything up for those character that doesnt have a full graphic rig, C: thanks in advance if you take the time.
Greetings!

**Comment by jasperges** [comment]
Thanks. I will close this issue, because it would be another addon. Maybe, if I have time someday, I might have a go at it. But I have a lot of other things on my list, that I would like to do first. So, don't keep you breath… ;)
