### ISSUE TITLE
Pose preview thumbnail with incorrect order

### ISSUE THREAD

**Issue by johantri** [jasperges/pose-thumbnails#23]
I'm using Blender 2.77a, Ubuntu 16.04 64bit. I got this error showing wrong order of the thumbnail and the pose itself.

Feel free to play around with this blend file

![samsul pose lib prev bug](https://cloud.githubusercontent.com/assets/13281082/17862162/40f9b6a0-68be-11e6-96eb-84634c1fd880.jpg)

[samsul.zip](https://github.com/jasperges/pose_lib_preview/files/430622/samsul.zip)

**Comment by sybrenstuvel** [comment]
If you just want a quick fix, look up the `os.listdir(...)` call, and replace it with this: `sorted(os.listdir(...))`.
