### ISSUE TITLE
Merging Pose Tools

### ISSUE THREAD

**Issue by adamearle** [jasperges/pose-thumbnails#26]
Great work on your addon its really really great

The addon cancels out the use of the **"pose tools"** addon which is super handy. I would seriously consider merging the 2 add-ons.

Link to pose tools: Link: https://github.com/TheDuckCow/pose-tools

I can't help think that this addon is really close to being full featured. It just needs a little more love and it will be there. Seriously really great work on what you have done.

Can't wait to see this add in the future it will be amazing. I will be promoting it on the "_**Pagewood Studios 2D to CG community**_" here is the link: _https://plus.google.com/u/0/communities/109082330838575508881

An excellent addon for reference for Maya addon called "**Studio Library**" it is used for the kids show here in Australia called  **Figaro Pho** http://www.imdb.com/title/tt5016516/

Links related to studio library:
1. http://www.studiolibrary.com/
2. https://www.youtube.com/watch?v=lpaWrT7VXfM
3. https://www.youtube.com/watch?v=xejWubal_j8&feature=youtu.be
4. https://www.youtube.com/watch?v=kCv0XleJfjU

Seriously congratulations on what you have done beautiful work.

PS. Perhaps a refresh button on for the thumbnails would be amazing. Also any chance getting this to register grease pencil frames.

**Comment by adamearle** [comment]
Some other addons that you may want to consolidate into one. _(Perhaps you guys work together)_

**Comment by jasperges** [comment]
Thanks for the nice comments. Though, to be honest, I think there is a lot of room for improvement. At the moment I'm also talking to Luciano Muñoz about this addon. :)
I know 'Studio Library', we also use it at the studio I'm working at the moment. I still have to check it out some more. Because I'm not a character animator myself, I didn't use it so far.

I will also have a look at  'pose-tools', didn't know it.
EDIT: I just had a look at it. That functionality is almost exactly what I have on my wish list for this addon... :)

There is a refresh button by the way, isn't this doing what you want?

**Comment by adamearle** [comment]
Sorry for the late reply i just installed "pose thumbnail master" into blender 2.78. 

You're amazing.

**Comment by TheDuckCow** [comment]
@jasperges Piping in around the pose-tools. At this stage, is there any functionality that my addon has that this pose library doesn't yet? Happy to help accelerate that if not. Either way, I fully support directing individuals there to look towards this addon in its place as more actively updated and fully featured.

**Comment by jasperges** [comment]
@adamearle Thanks and you're welcome! About the Grease Pencil request: could you open a new issue and elaborate a bit on what you mean? Then I can have a look at it, although I'm not guaranteeing anything… ;) And feel free to open more issues if you find bugs or have other suggestions. I'm closing this issue for now.

@TheDuckCow As far as I can see, only the 'Mixed Paste' is not in my addon. But at the moment I also don't see it fitting in with my addon. For now it's still centered around thumbnails for poses, but that might change in the future. :)
