### ISSUE TITLE
Pose Thumbnail 0.2 problem

### ISSUE THREAD

**Issue by johantri** [jasperges/pose-thumbnails#27]
Hi Jasper. Just got update email for version 0.2 (Thank you very much) and immidiately download it. But error when i try to install it.

![pose thumbnail v02 error](https://cloud.githubusercontent.com/assets/13281082/18937984/6427f0e6-861f-11e6-8253-79ad86e243c8.jpg)

**Comment by jasperges** [comment]
Whoops, my mistake. Fixed now.

**Comment by johantri** [comment]
Wonderful, thank you! It works now ^__^ b

**Comment by jasperges** [comment]
Okay, cool. Let me know what you think of the new version.

Op 29 sep. 2016 07:34 schreef "johantri" notifications@github.com:
