### ISSUE TITLE
What to do when mixing a pose and auto keyframe insertion is on?

### ISSUE THREAD

**Issue by jasperges** [jasperges/pose-thumbnails#29]
What should be keyed when auto keyframe insertion is on when mixing a pose? It seems that the standard 'apply pose' operator uses the 'Available' keying set. But isn't it better to respect the active keying set and default to 'Available' when there is no active keying set?
Other options?

**Comment by TheDuckCow** [comment]
Hmmm that's a hard question to answer. I can see it either way. Definitely respecting the a rice set would be most in line with what blender normally does, but would be frustrating if the user selects a pose and sees it moving  but then not save the key frames. How does the built in pose library behave with auto key on and applying to selected bones that aren't keyed? Mixing poses should probably just reflect the same behavior whichever way that is imo

**Comment by jasperges** [comment]
Thanks for your opinion. I completely agree. I just did some more investigating and I think I now know what happens. Just implemented this.
