### ISSUE TITLE
Libs and thumbnails aren't

### ISSUE THREAD

**Issue by billreynish** [jasperges/pose-thumbnails#32]
Hi, neat addon, although I have this deal-breaking issue though: 
While the addon works as advertised in my rig files, it fails to load correctly when I link the rig into a scene. It cannot find the thumbnails, even though they are all set with relative paths. The Action itself loads from the rig, b

Any idea why this might be? 

Bizzarely, the thumbnails DO load if I first open the rig file, *then* open the scene with the linked rig.

**Comment by billreynish** [comment]
In the rig file:
<img width="862" alt="screen shot 2017-03-06 at 15 19 10" src="https://cloud.githubusercontent.com/assets/26225106/23614266/a24082f0-0282-11e7-9767-f16c69c248c4.png">

When linked into scene:
<img width="571" alt="screen shot 2017-03-06 at 15 19 41" src="https://cloud.githubusercontent.com/assets/26225106/23614286/b4af2b1c-0282-11e7-830a-870c6ee29442.png">

**Comment by billreynish** [comment]
If I click the button to make the library action local, I get this: 
<img width="914" alt="screen shot 2017-03-06 at 15 08 21" src="https://cloud.githubusercontent.com/assets/26225106/23614336/daf2f588-0282-11e7-81bd-c1a721ba9378.png">

**Comment by jasperges** [comment]
Hi, thanks for reporting. I didn't properly test linking yet...
I found the problem and will fix it. :)

**Comment by billreynish** [comment]
Oh, great. I would be eternally grateful if you could fix it!

Cheers

Will

**Comment by jasperges** [comment]
@billreynish For me it works now. If you still have problems, please let me know.

**Comment by billreynish** [comment]
Very impressive! Now it works!

Thankyou so much.

When enabling the addon, I get a warning though. The Addon still seems to work, but thought you should know anyway.

Cheers

**Comment by jasperges** [comment]
What is the warning you get?

**Comment by billreynish** [comment]
Ah, thought I had attached it, here it is:

<img width="1029" alt="screen shot 2017-03-07 at 15 42 20" src="https://cloud.githubusercontent.com/assets/26225106/23670080/d6f4e916-0366-11e7-8ed6-b142a084fc60.png">

**Comment by jasperges** [comment]
Did you try removing all versions and installing the latest version? And of course restart Blender?

**Comment by jasperges** [comment]
@billreynish Are you still getting this error?

**Comment by billreynish** [comment]
Tested again on a fresh user account with the official release of Blender. No error. Dunno why I got it before, but it could simply be because already had the old one installed. I think you can safely disregard it.

So anyway, it really works really well now! We are using your plugin on a little animation to great effect. Incredibly useful feature! Thanks again!

W

**Comment by jasperges** [comment]
Okay, cool! Glad to hear it's working fine. Good luck with the project.

j
