### ISSUE TITLE
Linear interpolation of matrix elements is a bad idea

### ISSUE THREAD

**Issue by sybrenstuvel** [jasperges/pose-thumbnails#38]
https://github.com/jasperges/pose_thumbnails/blob/e80726b23d7ee9d5245ac7914c3c0d5fadf90833/pose_thumbnails.py#L301

This performs interpolation of two poses by linear interpolation of the 16 components of the matrix. This is a bad idea and can cause unexpected results. The matrix should be decomposed and the components interpolated appropriately (linearly for translation, quaternion-SLERP for rotation, etc.). Also see [this answer on Stack Exchange](https://stackoverflow.com/a/3111872/875379).

**Comment by jasperges** [comment]
Thanks for pointing out this and other issues. At the moment I don't have time to look at them, but I will when I have time again.
