### ISSUE TITLE
Moving documentation to GitHub Wiki

### ISSUE THREAD

**Issue by TheDuckCow** [jasperges/pose-thumbnails#54]
Following on from the other conversation, the idea is to move / create more comprehensive documentation of the addon into the repo's wiki page. I will largely be copying from [this previous doc](https://docs.google.com/document/d/1H0HO0jcon1a6SPQQ52eoVs0RAmrTDq877XhW1Mxqjgw/edit#heading=h.fgcswo2ixhkj) I made, though updating to reflect the new UI change recently committed. 

My plan is to create these pages:
  - Home: 
    - Overview (section on home page)
    - Installation (section on home page)
  - Creating pose libraries
  - Using pose libraries
  - File and naming conventions

Let me know if you'd see it any differently.

**Comment by jasperges** [comment]
I think that's fine. Next week I might have some time myself to work on it. But all input from you is more then welcome.

(And - as you probably already noticed - I finally did the release 🎉 .)

**Comment by TheDuckCow** [comment]
Sure thing - I did a first stab largely copying over and slightly generalizing the wiki from the google doc shared. 

Would be useful to add screenshots of the steps and interfaces as I had, though we would need to decide where to place these files (the wiki requires links to images, can't just attach to the wiki itself). Some github repo's will just add the set of images to a subfolder in the repo itself, and if they are small / compressed it wouldn't be a terrible idea to have it all in the same place. Alternate is to host in a separate location (link could always break though).

So, your call on the direction.

**Comment by jasperges** [comment]
I updated the wiki with images from your document. The wiki is actually just another git repo, so you can easily add images. Furthermore i changed some little things here and there and made links relative.

Thanks again for your work. I will close this 'issue' now.
