### ISSUE TITLE
Addon doesnt not work in the current stable build of 2.8

### ISSUE THREAD

**Issue by TheChrisHatfield** [jasperges/pose-thumbnails#57]
When installing the addon via both methods. Blender 2.8 doesn't not load the addon or any of the py scripts. Using the current stable build of Blender 2.8

**Comment by TheDuckCow** [comment]
Not the maintainer here, but I know that a branch was created to support 2.8 - [try this one](https://gitlab.com/blender-institute/pose-thumbnails).
