### ISSUE TITLE
Addon not working in 2.83

### ISSUE THREAD

**Issue by amshiv** [jasperges/pose-thumbnails#58]
Hi,
The addon is not working in 2.83.
thanks

**Comment by TheDuckCow** [comment]
You should refer to the 2.8 updated version of this addon here, maintained by the Blender Foundation: https://gitlab.com/blender-institute/pose-thumbnails

Just confirmed myself it's working in 2.83 specifically too.

**Comment by amshiv** [comment]
Thank yoy very much, i will try it asap.
