### ISSUE TITLE
[idea] generate thumbnail automatically

### ISSUE THREAD

**Issue by johantri** [jasperges/pose-thumbnails#7]
Hi Jasper,

Thank you so much for your work! I think this addon needs a lot of love :)

Just an idea to improve this addon, i think it will be awesome if we can generate thumbnail automatically (i'm sure you already think about that).

Another idea is to have animation cycle library included. With .gif thumbnail (probably) we can see what kind of animation clip when the mouse is hovering. and apply (insert) the animation to the character at a certain frame.

Cheers,
Johan

**Comment by jasperges** [comment]
I've split this issue in two seperate issues. The animation cycle library is now #8.
The automatic creation of thumbnails is in the works: [auto_create_thumbnail branch](/jasperges/pose_lib_preview/tree/auto_create_thumbnail). It mostly works, but I need to do some more cleanup and testing.
